SELECT FROM services;

INSERT INTO services
(id, name, serviceimg, servicedesc)
VALUES
(1, 'Amazon EC2', '/img/ec2.jpg', 'Forget the expensive physical servers with this AWS service that allows us to create virtual machines and manage other features of servers; such as storage, security, ports, etc. With Amazon EC2 you can create servers in minutes with your preferred operating system.
This way you will have more time to take care of your projects and spend less time maintaining your servers.'),
(2, 'Amazon RDS', '/img/rds.jpg', 'Amazon helps us to make our infrastructure less complicated, which is why it provides us with the RDS service. But what is it? With this service we will have dedicated instances for databases in a matter of minutes, fully managed by the AWS support team and capable of supporting multiple database engines such as SQL, PostgreSQL, SQL Server, etc …
Finally, we will forget all those hours of maintenance and support to our database servers!'),
(3, 'Amazon Simple Storage Service (S3)', '/img/s3.jpg'	, 'WS S3 also has high availability, so accessing your information is just a click away, with almost zero latency of 99.9999999999%. Surely now you wonder how expensive this service is? Well, we are pleased to inform you that it is impressively cheap. First, it has a free layer that includes 5 GB of storage and then starts at the cost of $ 0.023 / month for the first 50TB.'),
(4, 'Amazon Cloudfront', '/img/cf.jpg', 'Have you asked yourself how fast your website is? When your users connect, do they have to wait for seconds to open the page? With the Global Content Delivery Service, commonly known as CDN, Amazon is responsible for managing all your content, delivering it and presenting it efficiently. With a minimum latency and with its high integration with other AWS services.
Reaching your target users has never been so easy.'),
(5, 'Amazon VPC', '/img/vpc.jpg', 'Is my information at risk in the AWS cloud? The answer is NO, with the private network in the cloud your information will only be available to the people or systems that you authorize. With AWS VPC you can create a private virtual network in which your entire IT environment (infrastructure or services) will live totally isolated from the outside world. This way your information is free of exposure.'),
(6, 'Amazon SNS', '/img/sns.jpg', 'Going back to the developers’ issue, AWS services list offers us a very particular notification system that provides integration with any type of application, be it PHP, Python, Node, etc. With Amazon SNS we can send notifications to all our users on any platform, whether it is web or mobile on Android or iOS.'),
(7, 'AWS Beanstalk', '/img/bean.jpg', 'This is the most attractive service for developers. I know that as a developer you do not want to manage the infrastructure of your site, right? It is normal since its maintenance becomes tedious and difficult to solve any problem. AWS Elastic Beanstalk relieves all this; developers no longer need to manage the infrastructure and focus on developing their software or applications.'),
(8, 'AWS Lambda', '/img/lamb.jpg', 'If you, like many other developers, have the problem that your current infrastructure does not support the demands of your developments, then AWS Lambda is for you. This instance allows you to work in an environment highly capable of supporting any development you do. You just take care of the coding and AWS will be responsible for providing the necessary resources, climbing at the same time so that everything works correctly.'),
(9, 'AWS Autoscaling', '/img/as.jpg', 'With AutoScaling we can manage a fleet of servers which are capable of supporting all the traffic that our application demands. The service is totally free, the only thing charged is the number of instances for the time they run.'),
(10, 'AWS Elastic Cache', '/img/ec.jpg', 'Memory caching system of AWS. Elasticache supports Memcache and Redis.
Now that you have what it takes do not think more and venture to create extraordinary things with AWS and ClickIT.');